spring.application.name=deliveryPartner
server.port = 8082

# POSTGRES
spring.datasource.url=jdbc:postgresql://localhost:5433/delivery_partner_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# MONGODB
spring.data.mongodb.uri=mongodb://localhost:27017/delivery_partner_events_db

# KAFKA
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=delivery-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Explicitly trust the incoming package type or map it to the exact class
# Allow the JSON deserializer to parse any payload (or exactly the needed one)
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.deliveryService.service.kafka.OrderConfirmedEvent

# ACTUATOR
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#| Service               | URL                                            |
#| --------------------- | ---------------------------------------------- |
#| Postgres UI (PgAdmin) | [http://localhost:5050](http://localhost:5050) |
#Email: admin@delivery.com
#Password: admin123


#| Mongo UI              | [http://localhost:8081](http://localhost:8081) |
#| Kafka UI              | [http://localhost:8090](http://localhost:8090) |
